
version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      PORT: 5000
      FLASK_DEBUG: 1
      FLASK_APP: "app.py"
    volumes:
      - ./:/usr/src/